### ISSUE TITLE
'Initial deposit' should look at your current balance and show error if trying to set higher than current ballance

### ISSUE THREAD

**Issue by JasoonS** [wild-cards/dapp#18]
![image](https://user-images.githubusercontent.com/6032276/59827853-f4251280-9339-11e9-9d84-773f51c55de2.png)

This isn't so simple, it requires calculating how much deposit, and also gas cost + gas price (give reasonable value from eth-gas-station or something similar)

**Comment by DenhamPreen** [comment]
- Migrated to trello
