### ISSUE TITLE
We need to do the most basic form validation

### ISSUE THREAD

**Issue by JasoonS** [wild-cards/dapp#24]
https://rimble.consensys.design/components/rimble-ui/Form

This needs to happen in 3 places. The buy form, the update price form, and the deposit/withdrawal form. 

For now this will just have to be a rough approximate since we won't take into account gas costs etc. But it is good to at lest prevent submitting if the tx will definitely fail.

How to get the current user balance: https://github.com/JasoonS/dapp/blob/e57b515d7a1d59be7b8592d1a3939c4b377d4454/app/src/components/UpdateModal.tsx#L109  

How to get values from the smart contract (for withdrawal you will need the value from `depositAbleToWithdraw`. https://github.com/JasoonS/dapp/blob/e57b515d7a1d59be7b8592d1a3939c4b377d4454/app/src/components/UpdateModal.tsx#L109

The rest is just a case of maths.

**Comment by Stentonian** [comment]
Moved to Trello
