### ISSUE TITLE
Github pages deploy over writes custom domain field

### ISSUE THREAD

**Issue by DenhamPreen** [wild-cards/dapp#25]

**Comment by DenhamPreen** [comment]
![image](https://user-images.githubusercontent.com/26438203/60174338-1d014800-9811-11e9-89e0-c4c132f1d8c2.png)

Simple work around to re-set the value in github on each deploy

I believe its as simple as adding a line to the package.json file specifying a custom domain

**Comment by DenhamPreen** [comment]
I did some reading and we need to add the cname file to the public folder.

**Comment by moose-code** [comment]
I set this up for us initially a while back - it's quite straight forward I'm sure I can remember how to do it.

**Comment by JasoonS** [comment]
Fixed
